trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  BuildConfiguration: 'release'

steps:
- pwsh: |
    dotnet build --configuration $(BuildConfiguration)
  displayName: 'dotnet build $(BuildConfiguration)'
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
- pwsh: |
    dotnet test --logger trx
  displayName: 'dotnet test $(BuildConfiguration)'
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- pwsh: |
    dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/Lab src/Monyk.Lab.Main
    dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/Probe src/Monyk.Probe.Main
    dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/GroundControl src/Monyk.GroundControl.Main
  displayName: 'dotnet publish $(BuildConfiguration)'
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
- task: PublishBuildArtifacts@1