trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  BuildConfiguration: 'release'

steps:
- pwsh: |
    dotnet build --configuration $(BuildConfiguration) Monyk.sln
    dotnet test --logger trx Monyk.sln
    dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) src/Monyk.Lab.Main
    dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) src/Monyk.Probe.Main
    dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) src/Monyk.GroundControl.Main
  displayName: 'dotnet build+test $(BuildConfiguration)'
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishBuildArtifacts@1