version: '3.4'

services:
  monyk.groundcontrol.main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=42113
      - MONYK_Serilog__Seq__ServerUrl=http://seq:5341
      - MONYK_Communicator__RabbitMQ__Host=rabbitmq
      - MONYK_GroundControl__Database__Type=postgres
      - MONYK_GroundControl__Database__ConnectionString=Host=postgres;Username=postgres;Password=postgres;Database=groundcontrol
    ports:
      - "42112:80"
      - "42113:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  monyk.probe.main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=42123
      - MONYK_Serilog__Seq__ServerUrl=http://seq:5341
      - MONYK_Communicator__RabbitMQ__Host=rabbitmq
    ports:
      - "42122:80"
      - "42123:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  monyk.lab.main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=42133
      - MONYK_Serilog__Seq__ServerUrl=http://seq:5341
      - MONYK_Communicator__RabbitMQ__Host=rabbitmq
      - MONYK_Lab__GroundControlBaseUrl=http://monyk.groundcontrol.main
      - MONYK_Lab__Database__Type=postgres
      - MONYK_Lab__Database__ConnectionString=Host=postgres;Username=postgres;Password=postgres;Database=lab
    ports:
      - "42132:80"
      - "42133:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  rabbitmq:
    ports:
      - "15672:15672"

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
  
  seq:
    volumes:
      - "${APPDATA}/seq/data:/data"
    ports:
      - "5341:80"