version: '3.4'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "${APPDATA}/seq/data:/data"
    ports:
      - "5341:80"