Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
Monyk.Common.Communicator:
  RabbitMQ:
    Host: localhost
    VHost: '/'
    UserName: guest
    Password: guest