Seq:
  ServerUrl: <optional>
  
Communicator:
  RabbitMQ:
    Host: <required>
    VHost: <required>
    UserName: <required>
    Password: <required>
Lab:
  GroundControlBaseUrl: <required>
  ResultProcessors:
    SlackNotifier:
      WebHooks: <env. specific secrets (list)>