Seq:
  ServerUrl: http://seq:5341
  
Communicator:
  RabbitMQ:
    Host: <required>
    VHost: <required>
    UserName: <required>
    Password: <required>
Lab:
  GroundControlBaseUrl: <required>
  ResultProcessors:
    SlackNotifier:
      WebHooks: <env. specific secrets (list)>