Serilog:
  MinimumLevel: Debug
Communicator:
  RabbitMQ:
    Host: localhost
    VHost: /
    UserName: guest
    Password: guest
Lab:
  GroundControlBaseUrl: http://localhost:42110
  Database:
    Type: sqlite
    ConnectionString: Data Source=Lab.db