Seq:
  ServerUrl: http://localhost:5341

Communicator:
  RabbitMQ:
    Host: localhost
    VHost: /
    UserName: guest
    Password: guest
Lab:
  GroundControlBaseUrl: http://localhost:42003