Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
Monyk.Lab.Main:
  GroundControlBaseUrl: http://monyk.groundcontrol.main/api/v1
Monyk.Common.Communicator:
  RabbitMQ:
    Host: localhost
    VHost: '/'
    UserName: guest
    Password: guest