Logging:
  LogLevel:
    Default: Warning
AllowedHosts: "*"
Monyk.Common.Communicator:
  RabbitMQ:
    Host: '<env. specific>'
    VHost: '<env. specific>'
    UserName: '<env. specific>'
    Password: '<env. specific secret>'
Monyk.Lab.Main:
  ResultProcessors:
    SlackNotifier:
      WebHooks: '<env. specific secrets (list)>'
        