Logging:
  LogLevel:
    Default: Warning
AllowedHosts: "*"
Monyk.GroundControl:
  DatabaseType: '<required, Sqlite|Postgres>'
Monyk.Common.Communicator:
  RabbitMQ:
    Host: '<required>'
    VHost: '<required>'
    UserName: '<required>'
    Password: '<required>'