Serilog:
  MinimumLevel: Debug
Communicator:
  RabbitMQ:
    Host: localhost
    VHost: /
    UserName: guest
    Password: guest
GroundControl:
  Database:
    Type: sqlite
    ConnectionString: Data Source=GroundControl.db