Communicator:
  RabbitMQ:
    Host: <required>
    VHost: <required>
    UserName: <required>
    Password: <required>
GroundControl:
  Database:
    Type: '<Sqlite|Postgres, required>'
    ConnectionString: <required>