Seq:
  ServerUrl: http://localhost:5341

Communicator:
  RabbitMQ:
    Host: localhost
    UserName: guest
    Password: guest
GroundControl:
  Database:
    Type: sqlite
    ConnectionString: Data Source=GroundControl.db