Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
Monyk.GroundControl:
  DatabaseType: sqlite
Monyk.Common.Communicator:
  RabbitMQ:
    Host: localhost
    VHost: '/'
    UserName: guest
    Password: guest
ConnectionStrings:
  MainDb: 'Data Source=monyk.db'