Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
Monyk.GroundControl:
  DatabaseType: sqlite
Monyk.Common.Communicator:
  RabbitMQ:
    Host: vulture.rmq.cloudamqp.com
    VHost: iegvyoic
    UserName: iegvyoic
ConnectionStrings:
  MainDb: 'Data Source=monyk.db'